# Generated by Django 5.0.2 on 2026-03-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, help_text='List your skills separated by commas', max_length=255),
        ),
    ]
