services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: skillswap_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

